---

apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug-v0.16.0
    args: ["--context=git://github.com/sagarshrestha24/dashboard",

    "--destination=sagark24/angulardashboard:v3"]

    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred2
        items:
          - key: .dockerconfigjson
            path: config.json

